/*
 * Copyright (C) 2023-2024 Objectos Software LTDA.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package objectos.petclinic.boot;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import org.h2.jdbcx.JdbcConnectionPool;

public final class PetClinicH2 {

  /**
   * https://github.com/spring-projects/spring-petclinic/blob/d8fcd11e677102a795326ef73df09b50a646f849/src/main/resources/db/h2/schema.sql
   */
  static final String SCHEMA = """
  DROP TABLE vet_specialties IF EXISTS;
  DROP TABLE vets IF EXISTS;
  DROP TABLE specialties IF EXISTS;
  DROP TABLE visits IF EXISTS;
  DROP TABLE pets IF EXISTS;
  DROP TABLE types IF EXISTS;
  DROP TABLE owners IF EXISTS;

  CREATE TABLE vets (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(30),
    last_name  VARCHAR(30)
  );
  CREATE INDEX vets_last_name ON vets (last_name);

  CREATE TABLE specialties (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80)
  );
  CREATE INDEX specialties_name ON specialties (name);

  CREATE TABLE vet_specialties (
    vet_id       INTEGER NOT NULL,
    specialty_id INTEGER NOT NULL
  );
  ALTER TABLE vet_specialties ADD CONSTRAINT fk_vet_specialties_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
  ALTER TABLE vet_specialties ADD CONSTRAINT fk_vet_specialties_specialties FOREIGN KEY (specialty_id) REFERENCES specialties (id);

  CREATE TABLE types (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(80)
  );
  CREATE INDEX types_name ON types (name);

  CREATE TABLE owners (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(30),
    last_name  VARCHAR_IGNORECASE(30),
    address    VARCHAR(255),
    city       VARCHAR(80),
    telephone  VARCHAR(20)
  );
  CREATE INDEX owners_last_name ON owners (last_name);

  CREATE TABLE pets (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(30),
    birth_date DATE,
    type_id    INTEGER NOT NULL,
    owner_id   INTEGER
  );
  ALTER TABLE pets ADD CONSTRAINT fk_pets_owners FOREIGN KEY (owner_id) REFERENCES owners (id);
  ALTER TABLE pets ADD CONSTRAINT fk_pets_types FOREIGN KEY (type_id) REFERENCES types (id);
  CREATE INDEX pets_name ON pets (name);

  CREATE TABLE visits (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pet_id      INTEGER,
    visit_date  DATE,
    description VARCHAR(255)
  );
  ALTER TABLE visits ADD CONSTRAINT fk_visits_pets FOREIGN KEY (pet_id) REFERENCES pets (id);
  CREATE INDEX visits_pet_id ON visits (pet_id);
  """;

  /**
   * https://github.com/spring-projects/spring-petclinic/blob/d8fcd11e677102a795326ef73df09b50a646f849/src/main/resources/db/h2/data.sql
   */
  static final String DATA = """
  INSERT INTO vets VALUES (default, 'James', 'Carter');
  INSERT INTO vets VALUES (default, 'Helen', 'Leary');
  INSERT INTO vets VALUES (default, 'Linda', 'Douglas');
  INSERT INTO vets VALUES (default, 'Rafael', 'Ortega');
  INSERT INTO vets VALUES (default, 'Henry', 'Stevens');
  INSERT INTO vets VALUES (default, 'Sharon', 'Jenkins');

  INSERT INTO specialties VALUES (default, 'radiology');
  INSERT INTO specialties VALUES (default, 'surgery');
  INSERT INTO specialties VALUES (default, 'dentistry');

  INSERT INTO vet_specialties VALUES (2, 1);
  INSERT INTO vet_specialties VALUES (3, 2);
  INSERT INTO vet_specialties VALUES (3, 3);
  INSERT INTO vet_specialties VALUES (4, 2);
  INSERT INTO vet_specialties VALUES (5, 1);

  INSERT INTO types VALUES (default, 'cat');
  INSERT INTO types VALUES (default, 'dog');
  INSERT INTO types VALUES (default, 'lizard');
  INSERT INTO types VALUES (default, 'snake');
  INSERT INTO types VALUES (default, 'bird');
  INSERT INTO types VALUES (default, 'hamster');

  INSERT INTO owners VALUES (default, 'George', 'Franklin', '110 W. Liberty St.', 'Madison', '6085551023');
  INSERT INTO owners VALUES (default, 'Betty', 'Davis', '638 Cardinal Ave.', 'Sun Prairie', '6085551749');
  INSERT INTO owners VALUES (default, 'Eduardo', 'Rodriquez', '2693 Commerce St.', 'McFarland', '6085558763');
  INSERT INTO owners VALUES (default, 'Harold', 'Davis', '563 Friendly St.', 'Windsor', '6085553198');
  INSERT INTO owners VALUES (default, 'Peter', 'McTavish', '2387 S. Fair Way', 'Madison', '6085552765');
  INSERT INTO owners VALUES (default, 'Jean', 'Coleman', '105 N. Lake St.', 'Monona', '6085552654');
  INSERT INTO owners VALUES (default, 'Jeff', 'Black', '1450 Oak Blvd.', 'Monona', '6085555387');
  INSERT INTO owners VALUES (default, 'Maria', 'Escobito', '345 Maple St.', 'Madison', '6085557683');
  INSERT INTO owners VALUES (default, 'David', 'Schroeder', '2749 Blackhawk Trail', 'Madison', '6085559435');
  INSERT INTO owners VALUES (default, 'Carlos', 'Estaban', '2335 Independence La.', 'Waunakee', '6085555487');

  INSERT INTO pets VALUES (default, 'Leo', '2010-09-07', 1, 1);
  INSERT INTO pets VALUES (default, 'Basil', '2012-08-06', 6, 2);
  INSERT INTO pets VALUES (default, 'Rosy', '2011-04-17', 2, 3);
  INSERT INTO pets VALUES (default, 'Jewel', '2010-03-07', 2, 3);
  INSERT INTO pets VALUES (default, 'Iggy', '2010-11-30', 3, 4);
  INSERT INTO pets VALUES (default, 'George', '2010-01-20', 4, 5);
  INSERT INTO pets VALUES (default, 'Samantha', '2012-09-04', 1, 6);
  INSERT INTO pets VALUES (default, 'Max', '2012-09-04', 1, 6);
  INSERT INTO pets VALUES (default, 'Lucky', '2011-08-06', 5, 7);
  INSERT INTO pets VALUES (default, 'Mulligan', '2007-02-24', 2, 8);
  INSERT INTO pets VALUES (default, 'Freddy', '2010-03-09', 5, 9);
  INSERT INTO pets VALUES (default, 'Lucky', '2010-06-24', 2, 10);
  INSERT INTO pets VALUES (default, 'Sly', '2012-06-08', 1, 10);

  INSERT INTO visits VALUES (default, 7, '2013-01-01', 'rabies shot');
  INSERT INTO visits VALUES (default, 8, '2013-01-02', 'rabies shot');
  INSERT INTO visits VALUES (default, 8, '2013-01-03', 'neutered');
  INSERT INTO visits VALUES (default, 7, '2013-01-04', 'spayed');
  """;

  private PetClinicH2() {}

  public static JdbcConnectionPool create() throws SQLException {
    return create(true);
  }

  public static JdbcConnectionPool createSchema() throws SQLException {
    return create(false);
  }

  private static JdbcConnectionPool create(boolean data) throws SQLException {
    JdbcConnectionPool ds;
    ds = JdbcConnectionPool.create("jdbc:h2:mem:", "sa", "sa");

    ds.setMaxConnections(4);

    try (Connection c = ds.getConnection()) {
      c.setAutoCommit(false);

      c.setTransactionIsolation(Connection.TRANSACTION_SERIALIZABLE);

      try (Statement s = c.createStatement()) {
        s.executeUpdate(SCHEMA);

        if (data) {
          s.executeUpdate(DATA);
        }
      }

      c.commit();
    }

    return ds;
  }

}